//App
export const CHANGE_APP_STATUS = 'CHANGE_APP_STATUS';
export const APP_LOADER = 'APP_LOADER';

//User
export const SET_USER_DATA = 'SET_USER_DATA';
export const CHANGE_APP_LANGUAGE = "CHANGE_APP_LANGUAGE";
export const SET_PATIENT_DETAILS = 'SET_PATIENT_DETAILS';
